# testing <- tabPanel("Testing",
#                      fluidRow(column(width = 1),
#                               column(width = 10,
#                                      h4("(Please wait a few seconds for the figures to load)"),
#                                      h4(textOutput("latest")),
#                                      h2(""),
#                                      h4("Note that some data are missing because the data source was unable to obtain the number of tests conducted on some of the days."),
#                                      h2(""),
#                                      #h2("Daily confirmed positive tests and total tests in India"),
#                                      #p("This figure provides the number of COVID-19 tests (light green) and positive tests (red). Data source: api.covid19india.org."),
#                                      #plotlyOutput("India_p8", height = "600px"),
#                                      #hr(),
#                                      #h2(""),
#                                      h2("Testing pattern across countries"),
#                                      p("This figure provides the pattern of testing across countries using cumulative tests
#                                        per thousand versus cumulative confirmed cases per million. Data sources: api.covid19india.org and ourworldindata.org/coronavirus"),
#                                      plotlyOutput("India_p9", height = "600px"),
#                                      hr(),
#                                      h2("Total tests across countries"),
#                                      p("This figure provides the number of COVID-19 tests (light green) and positive tests (red) across countries. Data source: api.covid19india.org."),
#                                      plotlyOutput("India_p10", height = "600px"),
#                                      hr(),
#                                      h2("Total confirmed positive tests and total tests in India over time"),
#                                      p("This figure provides the cumulative number of COVID-19 tests (light green) and positive tests (red) over time. Data source: api.covid19india.org."),
#                                      plotlyOutput("India_p11", height = "500px"),
#                                      # hr(),
#                                      # h2("Temporal testing pattern in India"),
#                                      # plotlyOutput("India_p15", height = "500px"),
#                                      #plotOutput("India_p14", height = "800px"),
#                                      hr()
#                               ),
#                               column(width = 1)
#                      )
# )
